add nested recycler view to home screen
The-Cupcake-team/Chicken-Masala pull request #102
Opened 2023-03-30 17:01 UTC by TarekIdrees

2023-03-30 20:38 UTC, Sajadio commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/adapter/HomeRecyclerAdapter.kt
> +                    .inflate(R.layout.item_horizontal_recipes, parent, false)
Use ViewBinding

2023-03-30 20:41 UTC, Sajadio commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/adapter/HomeRecyclerAdapter.kt
> +    private fun ItemViewPagerBinding.setupViewPager(
Don't use the private   extension  function  and don't use it inside the class 
the recommended uses of extension outside the class and call it in any class

2023-03-30 20:44 UTC, Sajadio commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/adapter/HomeRecyclerAdapter.kt
> +    private fun areItemsTheSame(i: Int, i1: Int, homeItems: List<HomeItem<Any>>): Boolean {
You don't need this function if you don't have BaseNestedRecyclerView

2023-03-30 20:45 UTC, Sajadio reviewed
apply this review and will make your code so clean

2023-03-30 20:46 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/enums/HomeItem.kt
don't use enums as packge can keep in adapter pakage

2023-03-30 20:50 UTC, AmeerAmjed commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/adapter/HomeRecyclerAdapter.kt
> +            val r = 1 - kotlin.math.abs(position)
move import **abs** to part , don't import same this away .

2023-03-30 20:52 UTC, AmeerAmjed commented on app/src/main/res/layout/item_view_pager.xml
> +            android:id="@+id/header_title"
rename id to text_view_header_title

2023-03-30 20:54 UTC, mustafa-sab3alarab requested changes

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +        val advices = GetHealthAdvicesUseCase(repository)(ADVICES_LIMIT)
use invoke function to be more readable

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +    override fun onChipClicked(chipId: Int) {
separate this into two functions

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +            when(chipId){
attention u use when in else (**bareq**)😃

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
>      companion object {
make it private

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/adapter/HomeRecyclerAdapter.kt
> +    companion object {
make it private

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/res/layout/item_vertical_recipes.xml
> +            android:id="@+id/card_image"
image_(...)

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/res/layout/item_vertical_recipes.xml
> +            android:id="@+id/recipe_name"
text_(...)

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/res/layout/item_vertical_recipes.xml
> +            android:id="@+id/cuisine_name"
text_(...)

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/res/layout/item_vertical_recipes.xml
> +            android:id="@+id/recipe_time"
text_(...)

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/res/layout/item_view_pager.xml
> +            android:id="@+id/header_title"
text_(....)

2023-03-30 20:54 UTC, mustafa-sab3alarab commented on app/src/main/res/layout/item_view_pager.xml
> +            android:id="@+id/view_all"
text_(..)

2023-03-30 21:11 UTC, Mohammedbih requested changes

2023-03-30 21:11 UTC, mosayed01 commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
remove white space

2023-03-30 21:11 UTC, mosayed01 commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +    override fun onCardClicked(id: Int) {
rename function to `onRecipeCardClick`

2023-03-30 21:11 UTC, mosayed01 commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +            itemsList = itemsList.take(3).toMutableList()
please solve redundant

2023-03-30 21:11 UTC, mosayed01 commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +    override fun onChipClicked(chipId: Int) {
separate body to separated functions.

2023-03-30 21:11 UTC, Mohammedbih commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +        return GetAllFoodUseCase(repository)()
u can use instance of the use case and call it whenever you need

2023-03-30 21:11 UTC, Mohammedbih commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeFragment.kt
> +
white spaces :(

2023-03-30 21:11 UTC, Mohammedbih commented on app/src/main/java/com/cupcake/chickenmasala/ui/fragment/home/HomeInteractorListener.kt
> +import com.google.android.material.chip.ChipGroup
I guess it's unused import

2023-03-31 23:07 UTC, Mohammedbih submitted a review, later dismissed

2023-04-01 20:28 UTC, AmeerAmjed approved these changes

2023-04-01 20:32 UTC, merged

2023-04-01 21:35 UTC, AmeerAmjed approved these changes